variables:
  var-vhubnetwork-region: canadacentral
  var-vhubnetwork-managementGroupId: BCHealth-Sbox-FraserHealth-Platform
  #var-hubnetwork-azfw-configurationFileName: hub-azfw/hub-network.parameters.json
  #var-hubnetwork-nva-configurationFileName: hub-nva/hub-network.parameters.json
  #var-hubnetwork-ngfw-configurationFileName: hub-ngfw/hub-network.parameters.json
  var-vhubnetwork-nva-configurationFileName: vwan-nva/vwan-nva.parameters.json
  var-vhubnetwork-subscriptionId: 1d5b5f8a-d3d1-4a17-b061-00bf1db56490
  #var-hubnetwork-azfwPolicy-configurationFileName: hub-azfw-policy/azure-firewall-policy.parameters.json
  var-logging-managementGroupId: BCHealth-Sbox-FraserHealth-Platform
  var-logging-subscriptionId: 79c549f2-2c83-42b4-981e-ac008c1810e9
  deploymentRegion: canadacentral
  #var-NHA-managementGroupId: BCHealth-NorthernHealth
  var-BCH-managementGroupId: BCHealth-Sbox
  #var-identity-managementGroupId: BCHealth-NorthernHealth-Platform
  #var-logging-diagnosticSettingsforNetworkSecurityGroupsStoragePrefix: pubsecnsg
  var-logging-configurationFileName: logging.parameters.json
  var-managementgroup-hierarchy: |-
    {
      "id": "c1af1e68-a1bd-444d-8668-df3c95fb76bb",
      "name": "Tenant Root Group",
      "children": [
        {
          "id": "BCHealth",
          "name": "BCHealth",
          "children": [
            {
              "id": "BCHealth-Platform",
              "name": "Platform",
              "children": [
                {
                  "id": "BCHealth-Platform-Management",
                  "name": "Management",
                  "children": []
                },
                {
                  "id": "BCHealth-Platform-Connectivity",
                  "name": "Connectivity",
                  "children": []
                },
                {
                  "id": "BCHealth-Platform-Identity",
                  "name": "Identity",
                  "children": []
                },
                {
                  "id": "BCHealth-Platform-SharedServices",
                  "name": "SharedServices",
                  "children": []
                },
                {
                  "id": "BCHealth-Platform-Security",
                  "name": "Security",
                  "children": []
                }
              ]
            },
            {
              "id": "BCHealth-NewSubscription",
              "name": "NewSubscription",
              "children": []
            },
            {
              "id": "BCHealth-FraserHealth",
              "name": "FraserHealth",
              "children": [
                {
                  "id": "BCHealth-FraserHealth-Platform",
                  "name": "Platform",
                  "children": []
                },
                {
                  "id": "BCHealth-FraserHealth-Application",
                  "name": "Application",
                  "children": [
                    {
                      "id": "BCHealth-FraserHealth-Application-Cloud",
                      "name": "Cloud",
                      "children": []
                    },
                    {
                      "id": "BCHealth-FraserHealth-Application-Hybrid",
                      "name": "Hybrid",
                      "children": []
                    },
                  ]
                },
                {
                  "id": "BCHealth-FraserHealth-Decommissioned",
                  "name": "Decommissioned",
                  "children": []
                }
              ]
            },
            {
              "id": "BCHealth-InteriorHealth",
              "name": "InteriorHealth",
              "children": [
                {
                  "id": "BCHealth-InteriorHealth-Platform",
                  "name": "Platform",
                  "children": []
                },
                {
                  "id": "BCHealth-InteriorHealth-Application",
                  "name": "Application",
                  "children": [
                    {
                      "id": "BCHealth-InteriorHealth-Application-Cloud",
                      "name": "Cloud",
                      "children": []
                    },
                    {
                      "id": "BCHealth-InteriorHealth-Application-Hybrid",
                      "name": "Hybrid",
                      "children": []
                    },
                  ]
                },
                {
                  "id": "BCHealth-InteriorHealth-Decommissioned",
                  "name": "Decommissioned",
                  "children": []
                }
              ]
            },
            {
              "id": "BCHealth-IslandHealth",
              "name": "IslandHealth",
              "children": [
                {
                  "id": "BCHealth-IslandHealth-Platform",
                  "name": "Platform",
                  "children": []
                },
                {
                  "id": "BCHealth-IslandHealth-Application",
                  "name": "Application",
                  "children": [
                    {
                      "id": "BCHealth-IslandHealth-Application-Cloud",
                      "name": "Cloud",
                      "children": []
                    },
                    {
                      "id": "BCHealth-IslandHealth-Application-Hybrid",
                      "name": "Hybrid",
                      "children": []
                    },
                  ]
                },
                {
                  "id": "BCHealth-IslandHealth-Decommissioned",
                  "name": "Decommissioned",
                  "children": []
                }
              ]
            },
            {
              "id": "BCHealth-MinistryOfHealth",
              "name": "MinistryOfHealth",
              "children": [
                {
                  "id": "BCHealth-MinistryOfHealth-Platform",
                  "name": "Platform",
                  "children": []
                },
                {
                  "id": "BCHealth-MinistryOfHealth-Application",
                  "name": "Application",
                  "children": [
                    {
                      "id": "BCHealth-MinistryOfHealth-Application-Cloud",
                      "name": "Cloud",
                      "children": []
                    },
                    {
                      "id": "BCHealth-MinistryOfHealth-Application-Hybrid",
                      "name": "Hybrid",
                      "children": []
                    },
                  ]
                },
                {
                  "id": "BCHealth-MinistryOfHealth-Decommissioned",
                  "name": "Decommissioned",
                  "children": []
                }
              ]
            },
            {
              "id": "BCHealth-NorthernHealth",
              "name": "NorthernHealth",
              "children": [
                {
                  "id": "BCHealth-NorthernHealth-Platform",
                  "name": "Platform",
                  "children": []
                },
                {
                  "id": "BCHealth-NorthernHealth-Application",
                  "name": "Application",
                  "children": [
                    {
                      "id": "BCHealth-NorthernHealth-Application-Cloud",
                      "name": "Cloud",
                      "children": []
                    },
                    {
                      "id": "BCHealth-NorthernHealth-Application-Hybrid",
                      "name": "Hybrid",
                      "children": []
                    },
                  ]
                },
                {
                  "id": "BCHealth-NorthernHealth-Decommissioned",
                  "name": "Decommissioned",
                  "children": []
                }
              ]
            },
            {
              "id": "BCHealth-ProvincialHealth",
              "name": "ProvincialHealth",
              "children": [
                {
                  "id": "BCHealth-ProvincialHealth-Platform",
                  "name": "Platform",
                  "children": []
                },
                {
                  "id": "BCHealth-ProvincialHealth-Application",
                  "name": "Application",
                  "children": [
                    {
                      "id": "BCHealth-ProvincialHealth-Application-Cloud",
                      "name": "Cloud",
                      "children": []
                    },
                    {
                      "id": "BCHealth-ProvincialHealth-Application-Hybrid",
                      "name": "Hybrid",
                      "children": []
                    },
                  ]
                },
                {
                  "id": "BCHealth-ProvincialHealth-Decommissioned",
                  "name": "Decommissioned",
                  "children": []
                }
              ]
            },
            {
              "id": "BCHealth-Sbox",
              "name": "Sbox",
              "children": [
                 {
                  "id": "BCHealth-Sbox-Platform",
                  "name": "Platform",
                  "children": [
                    {
                      "id": "BCHealth-Sbox-Platform-Management",
                      "name": "Management",
                      "children": []
                    },
                    {
                      "id": "BCHealth-Sbox-Platform-Connectivity",
                      "name": "Connectivity",
                      "children": []
                    },
                    {
                      "id": "BCHealth-Sbox-Platform-Identity",
                      "name": "Identity",
                      "children": []
                    },
                    {
                      "id": "BCHealth-Sbox-Platform-SharedServices",
                      "name": "SharedServices",
                      "children": []
                    },
                    {
                      "id": "BCHealth-Sbox-Platform-Security",
                      "name": "Security",
                      "children": []
                    }
                  ]
                },
                {
                  "id": "BCHealth-Sbox-NewSubscription",
                  "name": "NewSubscription",
                  "children": []
                },
                {
                  "id": "BCHealth-Sbox-FraserHealth",
                  "name": "FraserHealth",
                  "children": [
                    {
                      "id": "BCHealth-Sbox-FraserHealth-Platform",
                      "name": "Platform",
                      "children": []
                    },
                    {
                      "id": "BCHealth-Sbox-FraserHealth-Application",
                      "name": "Application",
                      "children": [
                        {
                          "id": "BCHealth-Sbox-FraserHealth-Application-Cloud",
                          "name": "Cloud",
                          "children": []
                        },
                        {
                          "id": "BCHealth-Sbox-FraserHealth-Application-Hybrid",
                          "name": "Hybrid",
                          "children": []
                        },
                      ]
                    },
                    {
                      "id": "BCHealth-Sbox-FraserHealth-Decommissioned",
                      "name": "Decommissioned",
                      "children": []
                    }
                  ]
                },
                {
                  "id": "BCHealth-Sbox-InteriorHealth",
                  "name": "InteriorHealth",
                  "children": [
                    {
                      "id": "BCHealth-Sbox-InteriorHealth-Platform",
                      "name": "Platform",
                      "children": []
                    },
                    {
                      "id": "BCHealth-Sbox-InteriorHealth-Application",
                      "name": "Application",
                      "children": [
                        {
                          "id": "BCHealth-Sbox-InteriorHealth-Application-Cloud",
                          "name": "Cloud",
                          "children": []
                        },
                        {
                          "id": "BCHealth-Sbox-InteriorHealth-Application-Hybrid",
                          "name": "Hybrid",
                          "children": []
                        },
                      ]
                    },
                    {
                      "id": "BCHealth-Sbox-InteriorHealth-Decommissioned",
                      "name": "Decommissioned",
                      "children": []
                    }
                  ]
                },
                {
                  "id": "BCHealth-Sbox-IslandHealth",
                  "name": "IslandHealth",
                  "children": [
                    {
                      "id": "BCHealth-Sbox-IslandHealth-Platform",
                      "name": "Platform",
                      "children": []
                    },
                    {
                      "id": "BCHealth-Sbox-IslandHealth-Application",
                      "name": "Application",
                      "children": [
                        {
                          "id": "BCHealth-Sbox-IslandHealth-Application-Cloud",
                          "name": "Cloud",
                          "children": []
                        },
                        {
                          "id": "BCHealth-Sbox-IslandHealth-Application-Hybrid",
                          "name": "Hybrid",
                          "children": []
                        },
                      ]
                    },
                    {
                      "id": "BCHealth-Sbox-IslandHealth-Decommissioned",
                      "name": "Decommissioned",
                      "children": []
                    }
                  ]
                },
                {
                  "id": "BCHealth-Sbox-MinistryOfHealth",
                  "name": "MinistryOfHealth",
                  "children": [
                    {
                      "id": "BCHealth-Sbox-MinistryOfHealth-Platform",
                      "name": "Platform",
                      "children": []
                    },
                    {
                      "id": "BCHealth-Sbox-MinistryOfHealth-Application",
                      "name": "Application",
                      "children": [
                        {
                          "id": "BCHealth-Sbox-MinistryOfHealth-Application-Cloud",
                          "name": "Cloud",
                          "children": []
                        },
                        {
                          "id": "BCHealth-Sbox-MinistryOfHealth-Application-Hybrid",
                          "name": "Hybrid",
                          "children": []
                        },
                      ]
                    },
                    {
                      "id": "BCHealth-Sbox-MinistryOfHealth-Decommissioned",
                      "name": "Decommissioned",
                      "children": []
                    }
                  ]
                },
                {
                  "id": "BCHealth-Sbox-NorthernHealth",
                  "name": "NorthernHealth",
                  "children": [
                    {
                      "id": "BCHealth-Sbox-NorthernHealth-Platform",
                      "name": "Platform",
                      "children": []
                    },
                    {
                      "id": "BCHealth-Sbox-NorthernHealth-Application",
                      "name": "Application",
                      "children": [
                        {
                          "id": "BCHealth-Sbox-NorthernHealth-Application-Cloud",
                          "name": "Cloud",
                          "children": []
                        },
                        {
                          "id": "BCHealth-Sbox-NorthernHealth-Application-Hybrid",
                          "name": "Hybrid",
                          "children": []
                        },
                      ]
                    },
                    {
                      "id": "BCHealth-Sbox-NorthernHealth-Decommissioned",
                      "name": "Decommissioned",
                      "children": []
                    }
                  ]
                },
                {
                  "id": "BCHealth-Sbox-ProvincialHealth",
                  "name": "ProvincialHealth",
                  "children": [
                    {
                      "id": "BCHealth-Sbox-ProvincialHealth-Platform",
                      "name": "Platform",
                      "children": []
                    },
                    {
                      "id": "BCHealth-Sbox-ProvincialHealth-Application",
                      "name": "Application",
                      "children": [
                        {
                          "id": "BCHealth-Sbox-ProvincialHealth-Application-Cloud",
                          "name": "Cloud",
                          "children": []
                        },
                        {
                          "id": "BCHealth-Sbox-ProvincialHealth-Application-Hybrid",
                          "name": "Hybrid",
                          "children": []
                        },
                      ]
                    },
                    {
                      "id": "BCHealth-Sbox-ProvincialHealth-Decommissioned",
                      "name": "Decommissioned",
                      "children": []
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  var-logging-region: canadacentral
  #var-identity-configurationFileName: identity.parameters.json
  #var-identity-region: canadacentral
  #var-identity-subscriptionId: f6276be4-3aa6-4b70-a1b0-60656adf4293

